name: rusher
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flame: 1.0.0-releasecandidate.13
  flame_audio: 1.0.0-rc.1
  hive: 2.0.4
  path_provider: 2.0.3
  provider: 6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: any
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  google_sign_in: ^5.2.1
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_lints: ^1.0.4
  hive_generator: 1.1.0
  build_runner: 2.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
